#!/usr/bin/env python3
with open('scrape-and-update.js', 'r') as f:
    content = f.read()

# Replace Cathay shopee block
old_shopee = "const shopee = data.filter(a => /蝦皮|Shopee|shopee/i.test(a.name));\n  html += '<div class=\"platform\" data-platform=\"shopee\"><div class=\"platform-name\">🦐 蝦皮購物</div>';\n  if (shopee.length > 0) {\n    shopee.forEach(act => {\n      const tags = act.needsInstallment ? '<span class=\"tag\">需分期</span>' : '';\n      const parsed = parseTiers(act.tiers, bank);\n      let tiersHtml = '';\n      if (parsed.length > 0 && parsed[0].threshold) {\n        parsed.forEach(p => {\n          if (p.threshold) tiersHtml += `<span><span class=\"label\">門檻：</span>${p.threshold}</span>`;\n          if (p.reward) tiersHtml += `<span><span class=\"label\">回饋：</span>${p.reward}</span>`;\n        });\n      } else {\n        // fallback: 直接輸出 tier\n        act.tiers.slice(0, 2).forEach(t => {\n          tiersHtml += `<span>${t}</span>`;\n        });\n      }\n      html += `<div class=\"activity\">\n        <div class=\"activity-title\">${act.name} ${tags}</div>\n        <div class=\"activity-info\">\n          ${act.period ? `<span><span class=\"label\">消費區間：</span>${act.period}</span>` : ''}\n          ${tiersHtml}\n          ${act.registration ? `<span><span class=\"label\">登錄：</span>${act.registration}${act.limit ? `（${act.limit}）` : ''}</span>` : ''}\n          ${act.limit && !act.registration ? `<span><span class=\"label\">${act.limit}</span></span>` : ''}\n          ${act.needsInstallment ? `<span><span class=\"label\">分期：</span>✅ 可</span>` : ''}\n        </div>\n      </div>`;\n    });\n  } else {\n    html += `<div class=\"activity\"><div class=\"activity-title\">⚠️ 無活動</div><div class=\"activity-info\"><span>本月無蝦皮相關活動</span></div></div>`;\n  }\n  html += '</div>';"

new_shopee = "const shopee = data.filter(a => /蝦皮|Shopee|shopee/i.test(a.name));\n  html += '<div class=\"platform\" data-platform=\"shopee\"><div class=\"platform-name\">🦐 蝦皮購物</div>';\n  if (shopee.length > 0) {\n    shopee.forEach(act => {\n      const parsed = parseTiers(act.tiers, bank);\n      let tierLines = '';\n      if (parsed.length > 0 && parsed[0].threshold) {\n        parsed.forEach(p => {\n          if (p.threshold && p.reward) {\n            tierLines += '<div class=\"tier-item\">' + p.threshold + ' / ' + p.reward + '</div>';\n          } else if (p.reward) {\n            tierLines += '<div class=\"tier-item\">' + p.reward + '</div>';\n          }\n        });\n      } else {\n        act.tiers.slice(0, 2).forEach(t => {\n          tierLines += '<div class=\"tier-item\">' + t + '</div>';\n        });\n      }\n      const tiersHtml = '<div class=\"tier-section\"><span class=\"label\">門檻/回饋：</span><div class=\"tier-items\">' + tierLines + '</div></div>';\n      html += '<div class=\"activity\">' +\n        '<div class=\"activity-title\">' + act.name + '</div>' +\n        '<div class=\"activity-info\">' +\n          tiersHtml +\n          (act.limit ? '<div><span class=\"label\">限量：</span>' + act.limit + '</div>' : '') +\n          (act.registration ? '<div><span class=\"label\">登錄：</span>' + act.registration + '</div>' : '') +\n          (act.stacking ? '<div><span class=\"label\">疊加：</span>' + act.stacking + '</div>' : '') +\n        '</div>' +\n      '</div>';\n    });\n  } else {\n    html += '<div class=\"activity\"><div class=\"activity-title\">⚠️ 無活動</div><div class=\"activity-info\"><span>本月無蝦皮相關活動</span></div></div>';\n  }\n  html += '</div>';"

if old_shopee in content:
    content = content.replace(old_shopee, new_shopee)
    print("Shopee replaced OK")
else:
    print("Shopee NOT found")

# Replace Cathay momo block
old_momo = "const momo = data.filter(a => /momo|Momo/i.test(a.name));\n  html += '<div class=\"platform\" data-platform=\"momo\"><div class=\"platform-name\">🛍️ momo購物</div>';\n  if (momo.length > 0) {\n    momo.forEach(act => {\n      const tags = act.needsInstallment ? '<span class=\"tag\">需分期</span>' : '';\n      const parsed = parseTiers(act.tiers, bank);\n      let tiersHtml = '';\n      if (parsed.length > 0 && parsed[0].threshold) {\n        parsed.forEach(p => {\n          if (p.threshold) tiersHtml += `<span><span class=\"label\">門檻：</span>${p.threshold}</span>`;\n          if (p.reward) tiersHtml += `<span><span class=\"label\">回饋：</span>${p.reward}</span>`;\n        });\n      } else {\n        act.tiers.slice(0, 2).forEach(t => {\n          tiersHtml += `<span>${t}</span>`;\n        });\n      }\n      html += `<div class=\"activity\">\n        <div class=\"activity-title\">${act.name} ${tags}</div>\n        <div class=\"activity-info\">\n          ${act.period ? `<span><span class=\"label\">消費區間：</span>${act.period}</span>` : ''}\n          ${tiersHtml}\n          ${act.registration ? `<span><span class=\"label\">登錄：</span>${act.registration}${act.limit ? `（${act.limit}）` : ''}</span>` : ''}\n          ${act.needsInstallment ? `<span><span class=\"label\">分期：</span>✅ 可</span>` : ''}\n        </div>\n      </div>`;\n    });\n  } else {\n    html += `<div class=\"activity\"><div class=\"activity-title\">⚠️ 無活動</div><div class=\"activity-info\"><span>本月無momo相關活動</span></div></div>`;\n  }\n  html += '</div>';"

new_momo = "const momo = data.filter(a => /momo|Momo/i.test(a.name));\n  html += '<div class=\"platform\" data-platform=\"momo\"><div class=\"platform-name\">🛍️ momo購物</div>';\n  if (momo.length > 0) {\n    momo.forEach(act => {\n      const parsed = parseTiers(act.tiers, bank);\n      let tierLines = '';\n      if (parsed.length > 0 && parsed[0].threshold) {\n        parsed.forEach(p => {\n          if (p.threshold && p.reward) {\n            tierLines += '<div class=\"tier-item\">' + p.threshold + ' / ' + p.reward + '</div>';\n          } else if (p.reward) {\n            tierLines += '<div class=\"tier-item\">' + p.reward + '</div>';\n          }\n        });\n      } else {\n        act.tiers.slice(0, 2).forEach(t => {\n          tierLines += '<div class=\"tier-item\">' + t + '</div>';\n        });\n      }\n      const tiersHtml = '<div class=\"tier-section\"><span class=\"label\">門檻/回饋：</span><div class=\"tier-items\">' + tierLines + '</div></div>';\n      html += '<div class=\"activity\">' +\n        '<div class=\"activity-title\">' + act.name + '</div>' +\n        '<div class=\"activity-info\">' +\n          tiersHtml +\n          (act.limit ? '<div><span class=\"label\">限量：</span>' + act.limit + '</div>' : '') +\n          (act.registration ? '<div><span class=\"label\">登錄：</span>' + act.registration + '</div>' : '') +\n          (act.stacking ? '<div><span class=\"label\">疊加：</span>' + act.stacking + '</div>' : '') +\n        '</div>' +\n      '</div>';\n    });\n  } else {\n    html += '<div class=\"activity\"><div class=\"activity-title\">⚠️ 無活動</div><div class=\"activity-info\"><span>本月無momo相關活動</span></div></div>';\n  }\n  html += '</div>';"

if old_momo in content:
    content = content.replace(old_momo, new_momo)
    print("Momo replaced OK")
else:
    print("Momo NOT found")

with open('scrape-and-update.js', 'w') as f:
    f.write(content)
print("Done")
